language: cpp

compiler: 
    - gcc
    - clang  

before_install:
    # g++4.8
    - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

    # clang 3.5
#    - if [ "$cxx" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
    - if [ "$cxx" == "clang++" ]; then echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" | sudo tee -a /etc/apt/sources.list; fi
    - if [ "$cxx" == "clang++" ]; then echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main" | sudo tee -a /etc/apt/sources.list; fi

    # Cmake
    - sudo add-apt-repository -y ppa:kalakris/cmake

    - sudo apt-get update -qq
    - sudo pip install cpp-coveralls

install:
    # g++4.8
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

    # clang 3.5
#    - if [ "$CXX" == "clang++" ]; then sudo apt-get install -qq clang-3.5; fi
    - if [ "$CXX" == "clang++" ]; then sudo apt-get install -qq clang-3.5 libclang-3.5-dev; fi
    - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.5"; fi

    # CMake newest version
    - sudo apt-get install --allow-unauthenticated -qq cmake

before_script:
    - wget https://googletest.googlecode.com/files/gtest-1.7.0.zip -O /tmp/gtest.zip
    - unzip /tmp/gtest.zip && cd gtest-1.7.0
    - mkdir build && cd build && cmake -DBUILD_SHARED_LIBS=ON .. && make && sudo mv libg* /usr/local/lib
    - cd .. && sudo cp include/gtest /usr/local/include -R
    - cd .. && bash travis/cmake.sh

script:
    - cd build
    - make
    - bin/test_all
    - if [ "$CXX" = "g++" ]; then coveralls -E tests; fi
