SET(MOD_CORE_DEPS )
SET(MOD_CALIB_DEPS	CORE)
SET(MOD_AI_DEPS		CORE)
SET(MOD_AV_DEPS		CORE)
SET(MOD_VIDEO_DEPS	CORE)
SET(MOD_GEOREF_DEPS	CORE CALIB)
SET(MOD_SENSORS_DEPS CORE)

MACRO(check_dependencies module)
   FOREACH(dep ${MOD_${module}_DEPS})
      IF (NOT ${BUILD_MODULE_${dep}})
         MESSAGE(STATUS "Dependence ${dep} of ${module} is not enabled. ${module} will be disabled")
         SET(BUILD_MODULE_${module} OFF)
      ENDIF()
   ENDFOREACH()
ENDMACRO()

if (BUILD_MODULE_CALIB)
   check_dependencies("CALIB")
endif()
if (BUILD_MODULE_AI)
   check_dependencies("AI")
endif()
if (BUILD_MODULE_AV)
   check_dependencies("AV")
endif()
if (BUILD_MODULE_VIDEO)
   check_dependencies("VIDEO")
endif()
if (BUILD_MODULE_GEOREF)
   check_dependencies("GEOREF")
endif()
if (BUILD_MODULE_SENSORS)
   check_dependencies("SENSORS")
endif()
